# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultDialog(object):
    def setupUi(self, ResultDialog):
        ResultDialog.setObjectName("ResultDialog")
        ResultDialog.resize(844, 460)
        self.tableWidget = QtWidgets.QTableWidget(ResultDialog)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 851, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(ResultDialog)
        self.pushButton.setGeometry(QtCore.QRect(0, 410, 851, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(19)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(ResultDialog)
        QtCore.QMetaObject.connectSlotsByName(ResultDialog)

    def retranslateUi(self, ResultDialog):
        _translate = QtCore.QCoreApplication.translate
        ResultDialog.setWindowTitle(_translate("ResultDialog", "结果"))
        self.pushButton.setText(_translate("ResultDialog", "插入"))
